name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Clean working directory
      run: git clean -fdx

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Build the site
      run: |
        if [ -f package.json ]; then
          npm run build
        fi

    - name: Debug Git Configuration
      run: |
        git config --list
        git status
        git branch
        git remote -v

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Adjust this if your build directory is different

    - name: Debug Git Post-Deployment
      run: |
        git status
        git branch
        git remote -v

